
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/team02-s26-14
owner: ucsb-cs156-s26
repo_name: team02-s26-14
pull_requests: [{"author":{"id":"U_kgDOCVIAYQ","is_bot":false,"login":"ncontreras1","name":""},"headRefName":"Nathan-DCMenuItem-addIndexPage","number":101,"title":"Add Index page for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-s26/team02-s26-14/pull/101"},{"author":{"id":"U_kgDOCVIAYQ","is_bot":false,"login":"ncontreras1","name":""},"headRefName":"Nathan-DCMenuItem-addCreatePage","number":100,"title":"Add Create page for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-s26/team02-s26-14/pull/100"},{"author":{"id":"U_kgDOCVIAYQ","is_bot":false,"login":"ncontreras1","name":""},"headRefName":"Nathan-DCMenuItem-addPlaceholders","number":99,"title":"Add placeholder pages for UCSBDiningCommonsMenuItem Table","url":"https://github.com/ucsb-cs156-s26/team02-s26-14/pull/99"},{"author":{"id":"U_kgDOC5aSLg","is_bot":false,"login":"BennyZll","name":""},"headRefName":"bennny-index-page-for-UCSBOrganization","number":98,"title":"Bennny index page for ucsb organization","url":"https://github.com/ucsb-cs156-s26/team02-s26-14/pull/98"},{"author":{"id":"U_kgDOCujYag","is_bot":false,"login":"AbhijeetDutta1","name":"Abhijeet Dutta"},"headRefName":"abhi-req-CrPage","number":96,"title":"abhi - made create page logic","url":"https://github.com/ucsb-cs156-s26/team02-s26-14/pull/96"},{"author":{"id":"U_kgDODhRx4g","is_bot":false,"login":"AlessandroBa","name":"Alessandro"},"headRefName":"ale-article-edit-page","number":87,"title":"Ale article edit page","url":"https://github.com/ucsb-cs156-s26/team02-s26-14/pull/87"},{"author":{"id":"U_kgDODhRx4g","is_bot":false,"login":"AlessandroBa","name":"Alessandro"},"headRefName":"ale-index-article-page","number":86,"title":"Ale index article page","url":"https://github.com/ucsb-cs156-s26/team02-s26-14/pull/86"},{"author":{"id":"U_kgDODhRx4g","is_bot":false,"login":"AlessandroBa","name":"Alessandro"},"headRefName":"ale-create-article-page","number":80,"title":"Ale create article page","url":"https://github.com/ucsb-cs156-s26/team02-s26-14/pull/80"},{"author":{"id":"U_kgDODhRx4g","is_bot":false,"login":"AlessandroBa","name":"Alessandro"},"headRefName":"ale-article-placeholders-pages","number":78,"title":"add placeholder pages for Index,Edit, Create for articles","url":"https://github.com/ucsb-cs156-s26/team02-s26-14/pull/78"}]
