
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/team02-s26-14
owner: ucsb-cs156-s26
repo_name: team02-s26-14
pull_requests: [{"author":{"id":"U_kgDOCuio_A","is_bot":false,"login":"VishvaAr","name":"Vishva"},"headRefName":"VishvaHelpRequestCreate","number":73,"title":"Vishva help request create","url":"https://github.com/ucsb-cs156-s26/team02-s26-14/pull/73"},{"author":{"id":"U_kgDOCuio_A","is_bot":false,"login":"VishvaAr","name":"Vishva"},"headRefName":"VishvaPlaceholders","number":72,"title":"added nav bar for help request","url":"https://github.com/ucsb-cs156-s26/team02-s26-14/pull/72"},{"author":{"id":"U_kgDOCuio_A","is_bot":false,"login":"VishvaAr","name":"Vishva"},"headRefName":"VishvaTable","number":71,"title":"Vishva HelpRequest-table","url":"https://github.com/ucsb-cs156-s26/team02-s26-14/pull/71"},{"author":{"id":"U_kgDOCujYag","is_bot":false,"login":"AbhijeetDutta1","name":"Abhijeet Dutta"},"headRefName":"abhi-recreq-form","number":70,"title":"Abhi recreq form","url":"https://github.com/ucsb-cs156-s26/team02-s26-14/pull/70"},{"author":{"id":"U_kgDOCujYag","is_bot":false,"login":"AbhijeetDutta1","name":"Abhijeet Dutta"},"headRefName":"abhi-fixtures","number":69,"title":"added recreq fixtures","url":"https://github.com/ucsb-cs156-s26/team02-s26-14/pull/69"},{"author":{"id":"U_kgDOCuio_A","is_bot":false,"login":"VishvaAr","name":"Vishva"},"headRefName":"VishvaForm","number":68,"title":"Vishva form","url":"https://github.com/ucsb-cs156-s26/team02-s26-14/pull/68"},{"author":{"id":"U_kgDOCuio_A","is_bot":false,"login":"VishvaAr","name":"Vishva"},"headRefName":"VishvaFixtures","number":66,"title":"Add fixtures for HelpRequest","url":"https://github.com/ucsb-cs156-s26/team02-s26-14/pull/66"},{"author":{"id":"U_kgDODhRx4g","is_bot":false,"login":"AlessandroBa","name":"Alessandro"},"headRefName":"ale-article-form","number":64,"title":"add form for Articles","url":"https://github.com/ucsb-cs156-s26/team02-s26-14/pull/64"},{"author":{"id":"U_kgDODhRx4g","is_bot":false,"login":"AlessandroBa","name":"Alessandro"},"headRefName":"ale-article-fixtures","number":63,"title":"add javascript fixtures for article table","url":"https://github.com/ucsb-cs156-s26/team02-s26-14/pull/63"}]
