
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/team02-s26-14
owner: ucsb-cs156-s26
repo_name: team02-s26-14
pull_requests: [{"author":{"id":"U_kgDOCujYag","is_bot":false,"login":"AbhijeetDutta1","name":"Abhijeet Dutta"},"headRefName":"abhi-end","number":131,"title":"Abhi end","url":"https://github.com/ucsb-cs156-s26/team02-s26-14/pull/131"},{"author":{"id":"U_kgDOCVIAYQ","is_bot":false,"login":"ncontreras1","name":""},"headRefName":"Nathan-DCMenuItem-addE2E","number":130,"title":"Add E2E test for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-s26/team02-s26-14/pull/130"},{"author":{"id":"U_kgDOCVIAYQ","is_bot":false,"login":"ncontreras1","name":""},"headRefName":"Nathan-DCMenuItem-addIT","number":129,"title":"Add integration test for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-s26/team02-s26-14/pull/129"},{"author":{"id":"U_kgDOCujYag","is_bot":false,"login":"AbhijeetDutta1","name":"Abhijeet Dutta"},"headRefName":"abhi-integration","number":128,"title":"added integration tests for recreq","url":"https://github.com/ucsb-cs156-s26/team02-s26-14/pull/128"},{"author":{"id":"U_kgDODhRx4g","is_bot":false,"login":"AlessandroBa","name":"Alessandro"},"headRefName":"ale-articles-e2e-tests","number":125,"title":"Ale articles e2e tests","url":"https://github.com/ucsb-cs156-s26/team02-s26-14/pull/125"},{"author":{"id":"U_kgDODhRx4g","is_bot":false,"login":"AlessandroBa","name":"Alessandro"},"headRefName":"ale-article-integration-tests","number":124,"title":"ale -add integration tests for Article Controller endpoints","url":"https://github.com/ucsb-cs156-s26/team02-s26-14/pull/124"},{"author":{"id":"U_kgDOC5aSLg","is_bot":false,"login":"BennyZll","name":""},"headRefName":"benny-end-to-end-test","number":119,"title":"Benny end to end test","url":"https://github.com/ucsb-cs156-s26/team02-s26-14/pull/119"},{"author":{"id":"U_kgDOC5aSLg","is_bot":false,"login":"BennyZll","name":""},"headRefName":"benny-integration-tests-for-UCSBOrganization","number":118,"title":"add integratioin test","url":"https://github.com/ucsb-cs156-s26/team02-s26-14/pull/118"}]
